<script setup lang="ts">
import{computed,onMounted,ref}from'vue';import{applyAtlasCoreRestore,createAtlasBackup,getDataTransferOperations,getPersonalDataSummary,previewAtlasRestore}from'../services/dataExportService';import type{AtlasBackup,DataTransferOperation,PersonalDataSummary,RestoreApply,RestorePreview}from'../types/dataExport'
const summary=ref<PersonalDataSummary|null>(null),loading=ref(true),exporting=ref(false),error=ref(''),backup=ref<AtlasBackup|null>(null)
const restoreFile=ref<File|null>(null),preview=ref<RestorePreview|null>(null),analyzing=ref(false)
const restoreResult=ref<RestoreApply|null>(null),applying=ref(false),confirmation=ref(''),backupDownloaded=ref(false)
const operations=ref<DataTransferOperation[]>([])
const total=computed(()=>summary.value?summary.value.profileFacts+summary.value.checkIns+summary.value.dailyActivities+summary.value.dailyDecisions+summary.value.recurringSchedules+summary.value.kneeChecks+summary.value.trainingSessions+summary.value.trainingExercises+summary.value.followUps+summary.value.goals+summary.value.cycles+summary.value.planChanges+summary.value.metrics+summary.value.measurements+summary.value.learningEntries+summary.value.sharedReports+summary.value.professionalFeedback:0)
const groups=computed(()=>summary.value?[{name:'Contexto y agenda',value:summary.value.checkIns+summary.value.dailyActivities+summary.value.dailyDecisions+summary.value.recurringSchedules,detail:`${summary.value.checkIns} check-ins · ${summary.value.dailyActivities} actividades · ${summary.value.recurringSchedules} horarios`},{name:'Entrenamiento',value:summary.value.trainingSessions+summary.value.trainingExercises+summary.value.followUps,detail:`${summary.value.trainingSessions} sesiones · ${summary.value.trainingExercises} ejercicios · ${summary.value.followUps} respuestas`},{name:'Salud y progreso',value:summary.value.kneeChecks+summary.value.metrics+summary.value.measurements,detail:`${summary.value.kneeChecks} controles · ${summary.value.measurements} mediciones`},{name:'Plan y aprendizaje',value:summary.value.goals+summary.value.cycles+summary.value.planChanges+summary.value.learningEntries,detail:`${summary.value.goals} objetivos · ${summary.value.learningEntries} entradas`},{name:'Colaboración',value:summary.value.sharedReports+summary.value.professionalFeedback,detail:`${summary.value.sharedReports} informes · ${summary.value.professionalFeedback} aportes`}]:[])
async function load(){loading.value=true;try{const[data,history]=await Promise.all([getPersonalDataSummary(),getDataTransferOperations()]);summary.value=data;operations.value=history}catch(e){error.value=e instanceof Error?e.message:'No se pudo cargar.'}finally{loading.value=false}}
async function generate(){exporting.value=true;error.value='';backupDownloaded.value=false;try{backup.value=await createAtlasBackup();operations.value=await getDataTransferOperations()}catch(e){error.value=e instanceof Error?e.message:'No se pudo exportar.'}finally{exporting.value=false}}
function download(){if(!backup.value)return;const url=URL.createObjectURL(backup.value.file);const link=document.createElement('a');link.href=url;link.download=backup.value.file.name;link.click();backupDownloaded.value=true;setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function share(){if(!backup.value)return;try{if(navigator.canShare?.({files:[backup.value.file]})){await navigator.share({title:'Respaldo de Proyecto Atlas',files:[backup.value.file]});backupDownloaded.value=true}else download()}catch(e){if(e instanceof DOMException&&e.name==='AbortError')return;error.value='No se pudo compartir el archivo; podés descargarlo.'}}
function chooseFile(event:Event){restoreFile.value=(event.target as HTMLInputElement).files?.[0]??null;preview.value=null;restoreResult.value=null;confirmation.value='';error.value=''}
async function analyze(){if(!restoreFile.value)return;analyzing.value=true;error.value='';try{preview.value=await previewAtlasRestore(restoreFile.value)}catch(e){preview.value=null;error.value=e instanceof Error?e.message:'No se pudo analizar.'}finally{analyzing.value=false}}
const previewStatus=computed(()=>preview.value?.status==='compatible'?'Compatible para la siguiente etapa':preview.value?.status==='nothing_to_restore'?'Sin registros faltantes':'Requiere revisión')
const coreMissing=computed(()=>preview.value?.modules.filter(x=>['profileFacts','checkIns','dailyActivities','dailyDecisions','recurringSchedules','kneeChecks','metricDefinitions','measurements','goals','cycles','trainingSessions','trainingExercises','trainingFollowUps','learningEntries','planChanges','sharedReports','professionalFeedback'].includes(x.key)).reduce((sum,x)=>sum+x.missing,0)??0)
const canApply=computed(()=>Boolean(restoreFile.value&&preview.value?.status==='compatible'&&preview.value.sameAccount&&coreMissing.value>0&&backup.value&&backupDownloaded.value&&confirmation.value==='RESTAURAR FALTANTES'))
const guideSteps=computed(()=>[{title:'Preparar una copia actual',detail:'Atlas genera el archivo y registra su huella.',done:Boolean(backup.value)},{title:'Guardarla fuera de Atlas',detail:'Descargá o compartí la copia antes de continuar.',done:backupDownloaded.value},{title:'Analizar el archivo anterior',detail:'Se comprueba origen, integridad y contenido sin escribir datos.',done:Boolean(preview.value)},{title:'Aplicar sólo los faltantes',detail:'La operación completa queda registrada y puede auditarse.',done:Boolean(restoreResult.value)}])
async function applyRestore(){if(!canApply.value||!restoreFile.value||!preview.value||!backup.value)return;applying.value=true;error.value='';try{restoreResult.value=await applyAtlasCoreRestore(restoreFile.value,preview.value.sha256,backup.value.sha256,confirmation.value);await load();preview.value=await previewAtlasRestore(restoreFile.value)}catch(e){error.value=e instanceof Error?e.message:'La restauración se canceló.'}finally{applying.value=false}}
const date=(value:string|null)=>value?new Date(value).toLocaleString('es-AR'):'Sin registros'
onMounted(load)
</script>
<template><section class="page data-center-page" :class="{muted:loading}"><div class="page-heading"><div><span class="eyebrow">Privacidad y portabilidad</span><h1>Mis datos</h1><p>Inventario y respaldo completo de tu historial en Proyecto Atlas.</p></div><span class="evidence-chip">Formato Atlas v1.0</span></div><div v-if="error" class="notice error">{{error}}</div>
<section v-if="summary" class="data-summary"><article class="panel data-total"><span class="eyebrow">Inventario actual</span><strong>{{total}}</strong><p>registros y elementos relacionados</p><small>Desde {{date(summary.oldestRecord)}}<br>Último cambio {{date(summary.latestRecord)}}</small></article><div class="data-groups"><article v-for="group in groups" :key="group.name" class="panel"><span>{{group.name}}</span><strong>{{group.value}}</strong><small>{{group.detail}}</small></article></div></section>
<section class="panel backup-panel"><div><span class="eyebrow">Copia portable</span><h2>Crear respaldo personal</h2><p>Genera un archivo JSON legible y estructurado con perfil, registros, entrenamientos, evaluaciones, decisiones e historial de colaboración.</p><ul><li>No contiene contraseña ni cookies.</li><li>No contiene los códigos secretos de enlaces compartidos.</li><li>Incluye registros archivados para preservar el historial.</li><li>La huella SHA-256 permite comprobar que el archivo no fue alterado.</li></ul></div><aside><div class="privacy-warning"><strong>Archivo sensible</strong><p>Guardalo en un lugar privado. Quien tenga el archivo podrá leer su contenido.</p></div><button class="primary-button" :disabled="exporting" @click="generate">{{exporting?'Preparando…':'Generar respaldo'}}</button></aside></section>
<section v-if="backup" class="panel backup-ready"><div><span class="eyebrow">Respaldo preparado</span><h2>{{backup.file.name}}</h2><p>{{(backup.file.size/1024).toFixed(1)}} KB · formato {{backup.formatVersion}}</p></div><div class="backup-actions"><button class="primary-button" @click="download">Descargar</button><button class="secondary-button" @click="share">Compartir / Guardar</button></div><label>Huella SHA-256<input :value="backup.sha256" readonly></label></section>
<section class="panel recovery-guide"><header><div><span class="eyebrow">Prueba guiada</span><h2>Recorrido seguro de recuperación</h2></div><strong>{{guideSteps.filter(x=>x.done).length}} / {{guideSteps.length}}</strong></header><div><article v-for="(step,index) in guideSteps" :key="step.title" :class="{done:step.done}"><span>{{step.done?'✓':index+1}}</span><div><strong>{{step.title}}</strong><p>{{step.detail}}</p></div><small>{{step.done?'Completado':'Pendiente'}}</small></article></div></section>
<section class="panel restore-panel"><div><span class="eyebrow">Paso 1 · sólo análisis</span><h2>Revisar un respaldo</h2><p>Seleccioná un archivo Atlas para validar su estructura y compararlo con esta cuenta. Este análisis no escribe, elimina ni reemplaza datos.</p><label class="restore-file">Archivo JSON<input type="file" accept="application/json,.json" @change="chooseFile"></label><small v-if="restoreFile">{{restoreFile.name}} · {{(restoreFile.size/1024).toFixed(1)}} KB</small></div><aside><div class="safe-analysis"><strong>Operación segura</strong><p>El botón únicamente genera una vista previa.</p></div><button class="secondary-button" :disabled="!restoreFile||analyzing" @click="analyze">{{analyzing?'Analizando…':'Analizar respaldo'}}</button></aside></section>
<section v-if="preview" class="panel restore-preview"><header><div><span class="eyebrow">Resultado del análisis</span><h2>{{previewStatus}}</h2><p>Exportado {{new Date(preview.exportedAt).toLocaleString('es-AR')}} · formato {{preview.formatVersion}}</p></div><span :class="preview.status">{{preview.totalMissing}} faltantes</span></header><div class="restore-facts"><article><span>Procedencia</span><strong>{{preview.sameAccount?'Misma cuenta':'Cuenta diferente'}}</strong></article><article><span>Contenido</span><strong>{{preview.totalBackupRecords}} registros</strong></article><article><span>Tamaño</span><strong>{{(preview.fileBytes/1024).toFixed(1)}} KB</strong></article></div><div v-if="preview.warnings.length" class="restore-warnings"><strong>Aspectos a revisar</strong><p v-for="warning in preview.warnings" :key="warning">{{warning}}</p></div><div class="restore-modules"><header><strong>Módulo</strong><span>Respaldo</span><span>Actual</span><span>Coinciden</span><span>Faltan</span></header><article v-for="item in preview.modules" :key="item.key"><strong>{{item.label}}</strong><span>{{item.backupRecords}}</span><span>{{item.currentRecords}}</span><span>{{item.alreadyPresent}}</span><span>{{item.missing}}</span></article></div><label>Huella calculada del archivo<input :value="preview.sha256" readonly></label><footer>Todos los módulos del respaldo Atlas son recuperables. Por seguridad, los enlaces compartidos restaurados quedan archivados y revocados; nunca vuelven a habilitar acceso externo.</footer></section>
<section v-if="preview&&preview.status==='compatible'&&preview.sameAccount&&coreMissing>0" class="panel restore-apply"><div><span class="eyebrow">Paso 2 · transacción protegida</span><h2>Restaurar {{coreMissing}} registros compatibles faltantes</h2><p>Atlas nunca reemplazará un identificador existente. Las coincidencias de fecha, nombre o protocolo se vinculan o se conservan como conflictos sin duplicar.</p><ol><li>Generá arriba un respaldo de la cuenta actual.</li><li>Descargalo o guardalo en el teléfono.</li><li>Escribí la frase de confirmación exacta.</li></ol><label>Confirmación<input v-model="confirmation" autocomplete="off" placeholder="RESTAURAR FALTANTES"></label></div><aside><div :class="['restore-safety-state',{ready:backup&&backupDownloaded}]"><strong>{{backup&&backupDownloaded?'Respaldo de seguridad confirmado':'Falta guardar el respaldo actual'}}</strong><p>{{backup&&backupDownloaded?backup.file.name:'Usá “Generar respaldo” y después “Descargar” o “Compartir / Guardar”.'}}</p></div><button class="primary-button" :disabled="!canApply||applying" @click="applyRestore">{{applying?'Restaurando…':'Restaurar sólo faltantes'}}</button><small>Si cualquier registro falla, toda la transacción se revierte.</small></aside></section>
<section v-if="restoreResult" class="panel restore-result"><span>✓</span><div><span class="eyebrow">Transacción completada</span><h2>{{restoreResult.restored}} registros restaurados</h2><p>{{restoreResult.alreadyPresent}} ya existían · {{restoreResult.conflicts}} conflictos omitidos</p><div><article v-for="item in restoreResult.modules" :key="item.key"><strong>{{item.label}}</strong><span>+{{item.restored}}</span><small>{{item.alreadyPresent}} existentes · {{item.conflicts}} conflictos</small></article></div><p v-if="restoreResult.deferredModules.length"><b>Pendientes para una etapa relacional:</b> {{restoreResult.deferredModules.join(' · ')}}</p></div></section>
<section class="panel transfer-history"><header><div><span class="eyebrow">Auditoría personal</span><h2>Historial de operaciones</h2><p>Últimas copias preparadas y restauraciones completadas.</p></div><span>{{operations.length}}</span></header><div v-if="operations.length"><article v-for="item in operations" :key="item.id"><span :class="item.operationType">{{item.operationType==='backup'?'Copia':'Restauración'}}</span><div><strong>{{item.fileName??(item.restored+' registros recuperados')}}</strong><small>{{date(item.createdAt)}} · huella {{item.sha256.slice(0,12)}}…</small></div><p v-if="item.operationType==='restore'">{{item.alreadyPresent}} existentes · {{item.conflicts}} conflictos</p><b>Completada</b></article></div><p v-else class="empty-history">Todavía no hay operaciones registradas.</p></section>
</section></template>
