<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import { getInsights } from '../services/insightsService'
import type { DecisionOutcome,InsightsOverview } from '../types/insights'

const data=ref<InsightsOverview|null>(null),loading=ref(true),error=ref('')
const maxLoad=computed(()=>Math.max(1,...(data.value?.days.map(x=>x.internalLoad)??[])))
const recentDays=computed(()=>data.value?.days.slice(-14)??[])
function shortDate(v:string){return new Date(`${v}T00:00:00`).toLocaleDateString('es-AR',{day:'2-digit',month:'2-digit'})}
function metric(v:number|null,suffix=''){return v===null?'Sin datos':`${v}${suffix}`}
function decisionLabel(value:string){return value==='as-planned'?'Mantener plan':value==='adjusted'?'Plan ajustado':value==='recovery'?'Recuperación':'Consulta previa'}
function outcomeLabel(value:string){return value==='helpful'?'Acompañó una mejora':value==='neutral'?'Sin cambio claro':value==='not-helpful'?'No resultó útil':'No concluyente'}
function learningQuery(item:DecisionOutcome){
  const pain=item.pain===null?'sin dato':`${item.pain}/10`,fatigue=item.fatigue===null?'sin dato':`${item.fatigue}/10`
  return{date:item.date,title:`Revisión de decisión · ${shortDate(item.date)}`,category:item.decision==='recovery'?'Recuperación':'Entrenamiento',observation:`Decisión registrada: ${decisionLabel(item.decision)}. Carga prevista: ${item.plannedLoad} UA. Entrenamiento realizado: ${item.trainingLoad} UA. Actividad externa: ${item.externalLoad} UA. Fatiga: ${fatigue}. Dolor: ${pain}.${item.hasPostSessionAttention?' Se registró una señal posterior para revisar.':''}`,source:'decision'}
}
onMounted(async()=>{try{data.value=await getInsights()}catch(e){error.value=e instanceof Error?e.message:'No se pudo abrir el análisis.'}finally{loading.value=false}})
</script>

<template>
  <section class="page insights-page" :class="{muted:loading}">
    <div class="page-heading"><div><span class="eyebrow">Carga y recuperación</span><h1>Tendencias personales</h1><p>Describe qué cambió en tus propios registros. No predice lesiones ni decide si debés entrenar.</p></div><span v-if="data" class="data-depth">{{data.dataDays}} días con datos</span></div>
    <div v-if="error" class="notice error">{{error}}</div>
    <template v-if="data">
      <div v-if="!data.hasEnoughData" class="notice insight-note">Atlas necesita al menos 7 días con información para que las tendencias sean más interpretables. Mientras tanto, muestra datos descriptivos.</div>
      <div class="insight-kpis">
        <article><span>Carga · 7 días</span><strong>{{data.load.current7Days}} UA</strong><small v-if="data.load.changePercent!==null">{{data.load.changePercent>0?'+':''}}{{data.load.changePercent}}% frente a la semana previa</small><small v-else>Sin semana previa comparable</small></article>
        <article><span>Sesiones</span><strong>{{data.load.sessionsCurrent7Days}}</strong><small>{{data.load.minutesCurrent7Days}} minutos registrados</small></article>
        <article><span>Fatiga promedio</span><strong>{{metric(data.wellbeing.averageFatigue,' / 10')}}</strong><small>Autorreporte · 7 días</small></article>
        <article><span>Recuperación posterior</span><strong>{{metric(data.wellbeing.averageRecovery,' / 5')}}</strong><small>Respuesta tras sesiones</small></article>
      </div>
      <div class="insight-grid">
        <article class="panel load-chart"><div class="panel-heading"><div><span class="eyebrow">Últimos 14 días</span><h2>Carga interna registrada</h2></div><span class="evidence-chip">minutos × RPE</span></div><div class="load-columns"><div v-for="d in recentDays" :key="d.date" class="load-column"><span>{{d.internalLoad||''}}</span><div><i :style="{height:`${Math.max(2,d.internalLoad/maxLoad*100)}%`}"></i></div><small>{{shortDate(d.date)}}</small></div></div><p class="chart-caption">Las unidades son una estimación interna útil para comparar tus sesiones. No representan carga articular ni riesgo de lesión.</p></article>
        <article class="panel signal-panel"><div class="panel-heading"><div><span class="eyebrow">Lectura explicable</span><h2>Señales</h2></div></div><div class="signal-list"><div v-for="s in data.signals" :key="s.title" class="insight-signal" :class="s.kind"><span>{{s.kind==='attention'?'!':s.kind==='observe'?'↗':'i'}}</span><div><strong>{{s.title}}</strong><p>{{s.detail}}</p><small>{{s.basis}}</small></div></div></div></article>
      </div>
      <article class="panel wellbeing-panel"><div class="panel-heading"><div><span class="eyebrow">Contexto subjetivo</span><h2>Promedios de los últimos 7 días</h2></div></div><div class="wellbeing-grid"><div><span>Sueño</span><strong>{{metric(data.wellbeing.averageSleepQuality,' / 5')}}</strong></div><div><span>Energía</span><strong>{{metric(data.wellbeing.averageEnergy,' / 5')}}</strong></div><div><span>Fatiga</span><strong>{{metric(data.wellbeing.averageFatigue,' / 10')}}</strong></div><div><span>Estrés</span><strong>{{metric(data.wellbeing.averageStress,' / 5')}}</strong></div><div><span>Dolor</span><strong>{{metric(data.wellbeing.averagePain,' / 10')}}</strong></div><div><span>Recuperación</span><strong>{{metric(data.wellbeing.averageRecovery,' / 5')}}</strong></div></div></article>
      <article class="panel period-comparison"><div class="panel-heading"><div><span class="eyebrow">Cambio personal · 7 frente a 21 días</span><h2>Período reciente y referencia previa</h2><p>Compara medianas sin mezclar los días recientes dentro de la referencia.</p></div><div class="comparison-coverage"><span>Reciente {{data.periodComparison.recentCheckIns}}/{{data.periodComparison.recentDays}} · {{data.periodComparison.recentCoveragePercent}}%</span><span>Previo {{data.periodComparison.baselineCheckIns}}/{{data.periodComparison.baselineDays}} · {{data.periodComparison.baselineCoveragePercent}}%</span></div></div><div v-if="data.periodComparison.factors.length" class="comparison-grid"><article v-for="factor in data.periodComparison.factors" :key="factor.key" :class="factor.position"><header><span>{{factor.label}}</span><em>{{factor.position==='above'?'Por encima del rango':factor.position==='below'?'Por debajo del rango':factor.position==='within'?'Dentro del rango':'Faltan datos'}}</em></header><strong>{{factor.recentMedian}}{{factor.unit}}</strong><p>Mediana previa {{factor.baselineMedian}}{{factor.unit}} · cambio {{factor.delta>0?'+':''}}{{factor.delta}}{{factor.unit}}</p><small>Rango previo {{factor.baselineLowerQuartile}}–{{factor.baselineUpperQuartile}}{{factor.unit}} · n={{factor.recentEntries}} reciente / {{factor.baselineEntries}} previo</small></article></div><p v-else class="list-empty">Todavía no hay datos en ambos períodos para compararlos.</p><footer>{{data.periodComparison.disclaimer}}</footer></article>
      <article class="panel variability-panel"><div class="panel-heading"><div><span class="eyebrow">Referencia personal · {{data.variability.windowDays}} días</span><h2>Tu variabilidad observada</h2><p>La mediana representa el centro de tus registros; el rango central contiene el 50% intermedio.</p></div><span class="evidence-chip">{{data.variability.checkInDays}} registros · {{data.variability.coveragePercent}}%</span></div><div v-if="data.variability.factors.length" class="variability-grid"><article v-for="factor in data.variability.factors" :key="factor.key"><span>{{factor.label}}</span><strong>{{factor.median}}{{factor.unit}}</strong><small>Rango central {{factor.lowerQuartile}}–{{factor.upperQuartile}}{{factor.unit}}</small><em>Total observado {{factor.minimum}}–{{factor.maximum}}{{factor.unit}} · n={{factor.entries}}</em></article></div><p v-else class="list-empty">Completá check-ins para empezar a construir tu referencia personal.</p><footer>{{data.variability.disclaimer}}</footer></article>
      <article class="panel learning-trends"><div class="panel-heading"><div><span class="eyebrow">Aprendizaje · 28 días</span><h2>Qué ocurrió después de aplicar acciones</h2><p>Distribución de tus seguimientos registrados; no clasifica decisiones como correctas o incorrectas.</p></div><RouterLink to="/bitacora" class="secondary-button">Abrir bitácora</RouterLink></div><div class="learning-trend-grid"><div><span>Revisadas</span><strong>{{data.learning.reviewedActions}}</strong><small>Con seguimiento registrado</small></div><div class="helpful"><span>Acompañó mejora</span><strong>{{data.learning.helpful}}</strong><small>Asociación observada</small></div><div><span>Sin cambio claro</span><strong>{{data.learning.neutral}}</strong><small>Resultado neutral</small></div><div><span>No resultó útil</span><strong>{{data.learning.notHelpful}}</strong><small>Según tu seguimiento</small></div><div><span>No concluyentes</span><strong>{{data.learning.inconclusive}}</strong><small>Información insuficiente</small></div><div :class="{attention:data.learning.dueActions}"><span>Acciones abiertas</span><strong>{{data.learning.openActions}}</strong><small>{{data.learning.dueActions}} para revisar</small></div></div><div v-if="data.learning.categories.length" class="learning-category-summary"><span v-for="category in data.learning.categories" :key="category.category">{{category.category}} <strong>{{category.reviewedActions}}</strong></span></div><section class="learning-patterns"><div><span class="eyebrow">Consistencia descriptiva</span><h3>Resultados repetidos o mixtos</h3><p>Se calcula desde 3 seguimientos por categoría. “Repetido” requiere 3 coincidencias y al menos 70%.</p></div><div v-if="data.learning.patterns.length"><article v-for="pattern in data.learning.patterns" :key="pattern.category" :class="pattern.state"><span>{{pattern.category}}</span><strong>{{pattern.state==='repeated'?'Resultado repetido':'Resultados mixtos'}}</strong><p>{{outcomeLabel(pattern.dominantOutcome)}} · {{pattern.outcomeCount}} de {{pattern.entries}} registros ({{pattern.sharePercent}}%)</p></article></div><p v-else class="list-empty">Todavía no hay tres seguimientos comparables dentro de una misma categoría.</p></section><footer>{{data.learning.disclaimer}}</footer></article>
      <article class="panel decision-history">
        <div class="panel-heading"><div><span class="eyebrow">Decisión y resultado</span><h2>Qué elegiste y qué ocurrió</h2><p>Relación descriptiva; no califica la decisión ni atribuye causas.</p></div><span class="evidence-chip">{{data.decisions.length}} decisiones</span></div>
        <div v-if="data.decisions.length" class="decision-outcomes">
          <article v-for="item in data.decisions" :key="item.date" :class="{attention:item.hasPostSessionAttention}">
            <header><div><span>{{shortDate(item.date)}}</span><strong>{{decisionLabel(item.decision)}}</strong><small>Contexto {{item.contextStatus}} · versión {{item.version}}</small></div><em v-if="item.hasPostSessionAttention">Revisar respuesta</em></header>
            <p>{{item.reason}}</p>
            <div><span>Prevista<strong>{{item.plannedLoad}} UA</strong></span><span>Entrenamiento<strong>{{item.trainingLoad}} UA</strong></span><span>Actividad externa<strong>{{item.externalLoad}} UA</strong></span><span>Carga total<strong>{{item.totalLoad}} UA</strong></span><span>Fatiga<strong>{{metric(item.fatigue,' / 10')}}</strong></span><span>Dolor<strong>{{metric(item.pain,' / 10')}}</strong></span></div>
            <RouterLink class="outcome-learning-link" :to="{path:'/bitacora',query:learningQuery(item)}">Crear reflexión en la bitácora →</RouterLink>
          </article>
        </div>
        <p v-else class="list-empty">Todavía no hay decisiones diarias para relacionar con resultados.</p>
      </article>
      <article class="panel evidence-panel"><div class="panel-heading"><div><span class="eyebrow">Trazabilidad</span><h2>Por qué Atlas muestra esto</h2></div></div><div class="evidence-list"><a v-for="e in data.evidence" :key="e.permanentId" :href="e.sourceUrl" target="_blank" rel="noopener"><span><em>{{e.topic}}</em><strong>{{e.title}}</strong><small>{{e.permanentId}}</small></span><p><b>Uso:</b> {{e.use}}<br><b>Límite:</b> {{e.limitation}}</p></a></div></article>
    </template>
  </section>
</template>

<style scoped>
.period-comparison,.variability-panel{margin-top:16px}.comparison-coverage{display:grid;gap:5px}.comparison-coverage span{padding:5px 7px;border-radius:7px;color:#53627a;background:#edf1f5;font-size:8px;font-weight:800}.comparison-grid,.variability-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:9px;margin-top:18px}.comparison-grid article,.variability-grid article{padding:13px;border-radius:11px;background:#f4f8fb}.comparison-grid article.above,.comparison-grid article.below{border:1px solid #d6e0eb;background:#f8fafc}.comparison-grid header{display:grid;gap:5px}.comparison-grid header span{color:#718096;font-size:9px}.comparison-grid header em{color:#53627a;font-size:7px;font-style:normal;font-weight:800}.comparison-grid article.insufficient{opacity:.68}.comparison-grid strong,.comparison-grid p,.comparison-grid small,.variability-grid span,.variability-grid strong,.variability-grid small,.variability-grid em{display:block}.comparison-grid strong{margin-top:8px;color:#243149;font-size:18px}.comparison-grid p{margin-top:5px;font-size:8px}.comparison-grid small{margin-top:5px;color:#8794a5;font-size:7px;line-height:1.4}.variability-grid span{color:#718096;font-size:10px}.variability-grid strong{margin-top:5px;color:#243149;font-size:18px}.variability-grid small{margin-top:5px;color:#52627a;font-size:8px}.variability-grid em{margin-top:4px;color:#8794a5;font-size:7px;font-style:normal}.period-comparison footer,.variability-panel footer{margin-top:12px;padding-top:10px;border-top:1px solid #e4eaf0;color:#7a899d;font-size:8px;line-height:1.5}@media(max-width:980px){.comparison-grid,.variability-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:620px){.comparison-grid,.variability-grid{grid-template-columns:1fr 1fr}.period-comparison .panel-heading{align-items:flex-start;flex-direction:column}}
</style>
