<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{deleteKneeCheck,getKneeOverview,saveKneeCheck}from'../services/healthService';import type{KneeCheck,KneeOverview,SaveKneeCheckRequest}from'../types/health'
const overview=ref<KneeOverview|null>(null),editing=ref<string|null>(null),loading=ref(true),error=ref(''),success=ref('')
const localInput=(value:Date|string)=>{const d=new Date(value),offset=d.getTimezoneOffset()*60000;return new Date(d.getTime()-offset).toISOString().slice(0,16)}
const initial=():SaveKneeCheckRequest=>({recordedAt:localInput(new Date()),context:'Control diario',side:'sin definir',painNow:0,painBest24H:0,painWorst24H:0,swelling:'ninguna',instability:false,locking:false,fullExtension:true,walkingCapacity:10,stairsCapacity:10,squatCapacity:10,notes:null})
const form=reactive<SaveKneeCheckRequest>(initial())
async function load(){loading.value=true;try{overview.value=await getKneeOverview()}catch(e){error.value=e instanceof Error?e.message:'No se pudo cargar.'}finally{loading.value=false}}
function reset(){editing.value=null;Object.assign(form,initial())}
function edit(x:KneeCheck){editing.value=x.id;Object.assign(form,{...x,recordedAt:localInput(x.recordedAt)});document.querySelector('.knee-form')?.scrollIntoView({behavior:'smooth'})}
async function submit(){error.value='';try{await saveKneeCheck(form,editing.value??undefined);success.value='Control funcional guardado.';reset();await load()}catch(e){error.value=e instanceof Error?e.message:'No se pudo guardar.'}}
async function remove(id:string){try{await deleteKneeCheck(id);await load()}catch(e){error.value=e instanceof Error?e.message:'No se pudo eliminar.'}}
const fmt=(v:string)=>new Intl.DateTimeFormat('es-AR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))
onMounted(load)
</script>
<template><section class="page knee-page" :class="{muted:loading}"><div class="page-heading"><div><span class="eyebrow">Salud musculoesquelética</span><h1>Rodilla y respuesta funcional</h1><p>Seguimiento personal de síntomas y función. No diagnostica ni reemplaza una evaluación profesional.</p></div><span class="evidence-chip">Autorreporte estructurado</span></div><div v-if="error" class="notice error">{{error}}</div><div v-if="success" class="notice atlas-success">{{success}}</div>
<div v-if="overview" class="knee-summary"><article :class="overview.trend.state"><span>Estado actual</span><strong>{{overview.trend.state==='attention'?'Atención':overview.trend.state==='observe'?'Observar':overview.trend.state==='stable'?'Estable':'Sin datos'}}</strong></article><article><span>Dolor actual</span><strong>{{overview.trend.latestPain??'—'}} / 10</strong></article><article><span>Función media</span><strong>{{overview.trend.latestFunction??'—'}} / 10</strong></article><article><span>Controles</span><strong>{{overview.trend.totalChecks}}</strong></article></div>
<article v-if="overview?.trend.reasons.length" class="panel knee-alert"><span>!</span><div><strong>Señales registradas</strong><p v-for="reason in overview.trend.reasons" :key="reason">{{reason}}</p><small>Si son nuevas, intensas o progresivas, considerá consultar a un profesional. Atlas no determina la causa.</small></div></article>
<div class="knee-layout"><form class="panel knee-form" @submit.prevent="submit"><div class="panel-heading"><div><span class="eyebrow">Control 0–48 horas</span><h2>{{editing?'Corregir control':'Nuevo control'}}</h2></div><button v-if="editing" type="button" class="small-button" @click="reset">Cancelar</button></div><div class="atlas-form-grid"><label>Momento<input v-model="form.recordedAt" type="datetime-local" required></label><label>Contexto<select v-model="form.context"><option>Control diario</option><option>Antes de entrenar</option><option>Después de entrenar</option><option>12 h posteriores</option><option>24 h posteriores</option><option>48 h posteriores</option><option>Después del trabajo</option></select></label><label>Lado<select v-model="form.side"><option>sin definir</option><option>derecho</option><option>izquierdo</option><option>bilateral</option></select></label><label>Inflamación<select v-model="form.swelling"><option>ninguna</option><option>leve</option><option>moderada</option><option>alta</option></select></label><label>Dolor actual<select v-model.number="form.painNow"><option v-for="n in 11" :key="n" :value="n-1">{{n-1}} / 10</option></select></label><label>Dolor mínimo 24 h<select v-model.number="form.painBest24H"><option v-for="n in 11" :key="n" :value="n-1">{{n-1}} / 10</option></select></label><label>Dolor máximo 24 h<select v-model.number="form.painWorst24H"><option v-for="n in 11" :key="n" :value="n-1">{{n-1}} / 10</option></select></label><label>Caminar<select v-model.number="form.walkingCapacity"><option v-for="n in 11" :key="n" :value="n-1">{{n-1}} / 10</option></select></label><label>Escaleras<select v-model.number="form.stairsCapacity"><option v-for="n in 11" :key="n" :value="n-1">{{n-1}} / 10</option></select></label><label>Sentadilla tolerada<select v-model.number="form.squatCapacity"><option v-for="n in 11" :key="n" :value="n-1">{{n-1}} / 10</option></select></label></div><div class="atlas-flag-row knee-flags"><label><input v-model="form.instability" type="checkbox"> Falseo/inestabilidad</label><label><input v-model="form.locking" type="checkbox"> Bloqueo</label><label><input v-model="form.fullExtension" type="checkbox"> Extensión completa</label></div><label>Notas<textarea v-model="form.notes" rows="3" placeholder="Qué actividad lo modificó o cualquier dato relevante"></textarea></label><button class="primary-button">{{editing?'Actualizar':'Guardar control'}}</button></form>
<aside class="panel knee-history"><div class="panel-heading"><div><span class="eyebrow">Evolución</span><h2>Controles recientes</h2></div></div><article v-for="x in overview?.checks" :key="x.id" :class="x.state"><div><strong>{{fmt(x.recordedAt)}}</strong><small>{{x.context}} · {{x.side}}</small></div><span>{{x.painNow}}/10</span><p>Máx. 24 h {{x.painWorst24H}} · Función {{Math.round((x.walkingCapacity+x.stairsCapacity+x.squatCapacity)/3)}}/10 · Inflamación {{x.swelling}}</p><div class="row-actions"><button class="small-button" @click="edit(x)">Editar</button><button class="small-button danger" @click="remove(x.id)">Eliminar</button></div></article><p v-if="!overview?.checks.length" class="list-empty">Todavía no hay controles funcionales.</p></aside></div>
<article class="panel knee-evidence"><span class="eyebrow">Base y límites</span><h2>Por qué se registran estos datos</h2><p>Dolor en 24 horas, derrame, rango, estabilidad y función son dominios usados en guías clínicas de rodilla. Atlas sólo ordena tu evolución; una prueba física, imagen o diagnóstico corresponde a profesionales.</p><div><a href="https://www.orthopt.org/uploads/content_files/files/Knee%20Sprain%20CPG%20-%202017.pdf" target="_blank">APTA/JOSPT · Knee Ligament Sprain CPG</a><a href="https://www.aaos.org/ampcpg" target="_blank">AAOS · Acute Meniscal Pathology CPG</a></div></article></section></template>
