<script setup lang="ts">
import{onMounted,reactive,ref}from'vue';import{getPlanning,saveCycle,saveGoal}from'../services/planningService';import type{Cycle,Goal,PlanningOverview}from'../types/planning'
const data=ref<PlanningOverview|null>(null),tab=ref<'goals'|'cycles'|'history'>('goals'),showGoal=ref(false),showCycle=ref(false),goalId=ref<string|null>(null),cycleId=ref<string|null>(null),error=ref(''),success=ref('');const today=new Date().toLocaleDateString('en-CA')
const goal=reactive({title:'',category:'Rendimiento',baselineValue:null as number|null,targetValue:null as number|null,unit:'',startDate:today,targetDate:null as string|null,status:'active',rationale:'',changeReason:'Creación inicial del objetivo',metricDefinitionId:null as string|null})
const cycle=reactive({name:'',startDate:today,endDate:today,focus:'',plannedSessionsPerWeek:3,status:'planned',notes:'',changeReason:'Creación inicial del ciclo'})
async function load(){try{data.value=await getPlanning()}catch(e){error.value=e instanceof Error?e.message:'No se pudo abrir el plan.'}}
function editGoal(x:Goal){goalId.value=x.id;Object.assign(goal,{...x,changeReason:''});showGoal.value=true}
function editCycle(x:Cycle){cycleId.value=x.id;Object.assign(cycle,{...x,changeReason:''});showCycle.value=true}
function resetGoal(){goalId.value=null;showGoal.value=false;Object.assign(goal,{title:'',category:'Rendimiento',baselineValue:null,targetValue:null,unit:'',startDate:today,targetDate:null,status:'active',rationale:'',changeReason:'Creación inicial del objetivo',metricDefinitionId:null})}
function resetCycle(){cycleId.value=null;showCycle.value=false;Object.assign(cycle,{name:'',startDate:today,endDate:today,focus:'',plannedSessionsPerWeek:3,status:'planned',notes:'',changeReason:'Creación inicial del ciclo'})}
async function submitGoal(){try{await saveGoal(goal,goalId.value??undefined);success.value='Objetivo guardado con trazabilidad.';resetGoal();await load()}catch(e){error.value=e instanceof Error?e.message:'No se pudo guardar.'}}
async function submitCycle(){try{await saveCycle(cycle,cycleId.value??undefined);success.value='Ciclo guardado con trazabilidad.';resetCycle();await load()}catch(e){error.value=e instanceof Error?e.message:'No se pudo guardar.'}}
const fmt=(v:string)=>new Date(`${v}T12:00:00`).toLocaleDateString('es-AR');const status=(v:string)=>v==='active'?'Activo':v==='completed'?'Completado':v==='paused'?'Pausado':'Planificado';const entityLabel=(v:string)=>v==='goal'?'Objetivo':v==='cycle'?'Ciclo':v==='session'?'Sesión':'Ejercicio'
onMounted(load)
</script>
<template><section class="page planning-page"><div class="page-heading"><div><span class="eyebrow">Dirección y estructura</span><h1>Plan maestro</h1><p>Define qué querés lograr, cómo se organiza el período y por qué cambia el plan.</p></div><div class="heading-actions"><button class="secondary-button" @click="showCycle=true;tab='cycles'">Nuevo ciclo</button><button class="primary-button" @click="showGoal=true;tab='goals'">Nuevo objetivo</button></div></div><div v-if="error" class="notice error">{{error}}</div><div v-if="success" class="notice atlas-success">{{success}}</div><div class="planning-tabs"><button :class="{active:tab==='goals'}" @click="tab='goals'">Objetivos · {{data?.goals.length??0}}</button><button :class="{active:tab==='cycles'}" @click="tab='cycles'">Ciclos · {{data?.cycles.length??0}}</button><button :class="{active:tab==='history'}" @click="tab='history'">Historial</button></div>
<form v-if="showGoal&&tab==='goals'" class="panel planning-form" @submit.prevent="submitGoal"><div class="panel-heading"><div><span class="eyebrow">{{goalId?'Nueva versión':'Definición'}}</span><h2>{{goalId?'Editar objetivo':'Nuevo objetivo'}}</h2></div><button type="button" class="icon-button" @click="resetGoal">×</button></div><div class="atlas-form-grid"><label>Título<input v-model="goal.title" required></label><label>Categoría<select v-model="goal.category"><option>Rendimiento</option><option>Fuerza</option><option>Resistencia</option><option>Composición corporal</option><option>Movilidad</option><option>Salud</option><option>Prueba policial</option></select></label><label>Valor inicial<input v-model.number="goal.baselineValue" type="number" step="0.01"></label><label>Valor objetivo<input v-model.number="goal.targetValue" type="number" step="0.01"></label><label>Unidad<input v-model="goal.unit" placeholder="kg, min, repeticiones..."></label><label>Indicador vinculado<select v-model="goal.metricDefinitionId"><option :value="null">Sin indicador</option><option v-for="metric in data?.metrics" :key="metric.id" :value="metric.id">{{metric.name}} · {{metric.unit}}</option></select></label><label>Estado<select v-model="goal.status"><option value="active">Activo</option><option value="paused">Pausado</option><option value="completed">Completado</option></select></label><label>Inicio<input v-model="goal.startDate" type="date" required></label><label>Fecha objetivo<input v-model="goal.targetDate" type="date"></label><label class="wide">Fundamento<textarea v-model="goal.rationale" rows="2"></textarea></label><label class="wide">Motivo de esta versión<input v-model="goal.changeReason" required placeholder="Por qué se crea o modifica"></label></div><button class="primary-button">Guardar objetivo</button></form>
<form v-if="showCycle&&tab==='cycles'" class="panel planning-form" @submit.prevent="submitCycle"><div class="panel-heading"><div><span class="eyebrow">{{cycleId?'Nueva versión':'Periodización'}}</span><h2>{{cycleId?'Editar ciclo':'Nuevo ciclo'}}</h2></div><button type="button" class="icon-button" @click="resetCycle">×</button></div><div class="atlas-form-grid"><label>Nombre<input v-model="cycle.name" required></label><label>Foco<input v-model="cycle.focus" required placeholder="Ej.: base aeróbica y fuerza general"></label><label>Inicio<input v-model="cycle.startDate" type="date" required></label><label>Fin<input v-model="cycle.endDate" type="date" required></label><label>Sesiones por semana<input v-model.number="cycle.plannedSessionsPerWeek" type="number" min="0" max="14"></label><label>Estado<select v-model="cycle.status"><option value="planned">Planificado</option><option value="active">Activo</option><option value="paused">Pausado</option><option value="completed">Completado</option></select></label><label class="wide">Notas<textarea v-model="cycle.notes" rows="2"></textarea></label><label class="wide">Motivo de esta versión<input v-model="cycle.changeReason" required></label></div><button class="primary-button">Guardar ciclo</button></form>
<div v-if="tab==='goals'" class="plan-card-grid"><article v-for="x in data?.goals" :key="x.id" class="panel plan-card"><div><span class="fact-status" :class="x.status">{{status(x.status)}}</span><em>v{{x.version}}</em></div><h2>{{x.title}}</h2><p>{{x.category}} · {{fmt(x.startDate)}}<template v-if="x.targetDate"> → {{fmt(x.targetDate)}}</template></p><div class="goal-values"><span><small>Base</small><strong>{{x.baselineValue??'—'}} {{x.unit}}</strong></span><b>→</b><span><small>Objetivo</small><strong>{{x.targetValue??'—'}} {{x.unit}}</strong></span></div><div v-if="x.metricName" class="plan-progress"><div><span>{{x.metricName}}</span><strong>{{x.latestValue??'Sin datos'}} {{x.unit}}</strong></div><i><b :style="{width:`${x.progressPercent??0}%`}"></b></i><small>{{x.progressPercent===null?'Faltan mediciones comparables':`${x.progressPercent}% del recorrido`}}<template v-if="x.latestDate"> · {{fmt(x.latestDate)}}</template></small></div><p v-else class="plan-no-link">Sin indicador vinculado</p><p v-if="x.rationale">{{x.rationale}}</p><button class="small-button" @click="editGoal(x)">Editar y crear versión</button></article><p v-if="!data?.goals.length" class="panel list-empty">Todavía no hay objetivos estructurados.</p></div>
<div v-if="tab==='cycles'" class="plan-card-grid"><article v-for="x in data?.cycles" :key="x.id" class="panel plan-card"><div><span class="fact-status" :class="x.status">{{status(x.status)}}</span><em>v{{x.version}}</em></div><h2>{{x.name}}</h2><p>{{fmt(x.startDate)}} → {{fmt(x.endDate)}}</p><strong>{{x.focus}}</strong><p>{{x.plannedSessionsPerWeek}} sesiones previstas por semana</p><div class="cycle-adherence"><strong>{{x.completedSessions}} / {{x.expectedSessions}}</strong><span>sesiones cumplidas hasta hoy</span><i><b :style="{width:`${Math.min(100,x.adherencePercent??0)}%`}"></b></i><small>{{x.adherencePercent===null?'El ciclo todavía no comenzó':`${x.adherencePercent}% de cumplimiento`}}</small></div><button class="small-button" @click="editCycle(x)">Editar y crear versión</button></article><p v-if="!data?.cycles.length" class="panel list-empty">Todavía no hay ciclos definidos.</p></div>
<article v-if="tab==='history'" class="panel plan-history"><div class="panel-heading"><div><span class="eyebrow">Auditoría personal</span><h2>Decisiones del plan</h2></div></div><div v-for="x in data?.changes" :key="x.id"><span>{{entityLabel(x.entityType)}} · v{{x.version}}</span><strong>{{x.summary}}</strong><p>{{x.reason}}</p><small>{{new Date(x.changedAt).toLocaleString('es-AR')}}</small></div><p v-if="!data?.changes.length" class="list-empty">El historial comenzará con la primera creación.</p></article></section></template>
