<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref } from 'vue'
import * as api from '../services/trainingService'
import type { TrainingOverview, TrainingSession } from '../types/training'
import { useAuthStore } from '../stores/auth'
const emptyOverview:TrainingOverview={upcoming:[],recent:[],pendingFollowUps:[],metrics:{sessionsLast7Days:0,minutesLast7Days:0,loadLast7Days:0,pendingFollowUps:0},goals:[],cycles:[]}
const overview=ref<TrainingOverview>(emptyOverview), selectedId=ref<string|null>(null), error=ref(''), success=ref(''), loading=ref(true), showNew=ref(false), showDuplicate=ref(false), duplicating=ref(false), showWeekCopy=ref(false), copyingWeek=ref(false), addingExercise=ref(false), completing=ref(false),editingSessionId=ref<string|null>(null),editingExerciseId=ref<string|null>(null)
const today=new Date().toLocaleDateString('en-CA')
const tomorrow=()=>{const date=new Date();date.setDate(date.getDate()+1);return date.toLocaleDateString('en-CA')}
const weekStart=(offset=0)=>{const date=new Date();const mondayOffset=(date.getDay()+6)%7;date.setDate(date.getDate()-mondayOffset+(offset*7));return date.toLocaleDateString('en-CA')}
const sessionForm=reactive({date:today,name:'',activityType:'Fuerza',plannedStartTime:null as string|null,plannedDurationMinutes:60,targetRpe:6,goal:'',notes:'',personalGoalId:null as string|null,trainingCycleId:null as string|null,changeReason:'Creación inicial de la sesión'})
const duplicateForm=reactive({date:tomorrow(),name:'',changeReason:'Sesión reutilizada desde una planificación existente'})
const weekForm=reactive({sourceWeekStart:weekStart(),targetWeekStart:weekStart(1),changeReason:'Planificación semanal reutilizada como referencia'})
const exerciseForm=reactive({name:'',category:'Fuerza',sets:3,repetitions:'10',loadKg:null as number|null,restSeconds:90,notes:'',changeReason:'Ejercicio agregado a la prescripción'})
const completeForm=reactive({actualDurationMinutes:60,sessionRpe:6,completionNotes:''})
const resultForms=reactive<Record<string,{completedSets:number;actualRepetitions:string;actualLoadKg:number|null;exerciseRpe:number|null}>>({})
const auth=useAuthStore()
const selected=computed(()=>[...(overview.value?.upcoming??[]),...(overview.value?.recent??[])].find(x=>x.id===selectedId.value)??null)
function fmt(value:string){return new Date(`${value}T00:00:00`).toLocaleDateString('es-AR',{weekday:'short',day:'2-digit',month:'short'})}
function setError(e:unknown){error.value=e instanceof Error?e.message:'Ocurrió un error.'}
function sync(s:TrainingSession){if(!overview.value)return; for(const list of [overview.value.upcoming,overview.value.recent,overview.value.pendingFollowUps]){const i=list.findIndex(x=>x.id===s.id);if(i>=0)list.splice(i,1)} if(s.status==='Completed')overview.value.recent.unshift(s);else overview.value.upcoming.unshift(s);selectedId.value=s.id; hydrateResults(s)}
function hydrateResults(s:TrainingSession){for(const x of s.exercises) resultForms[x.id]={completedSets:x.completedSets??x.plannedSets,actualRepetitions:x.actualRepetitions??x.plannedRepetitions,actualLoadKg:x.actualLoadKg??x.plannedLoadKg,exerciseRpe:x.exerciseRpe}}
async function load(){loading.value=true;try{overview.value=await api.getTrainingOverview();selectedId.value=overview.value.upcoming[0]?.id??overview.value.recent[0]?.id??null;if(selected.value)hydrateResults(selected.value)}catch(e){setError(e)}finally{loading.value=false}}
function resetSession(){editingSessionId.value=null;showNew.value=false;Object.assign(sessionForm,{date:today,name:'',activityType:'Fuerza',plannedStartTime:null,plannedDurationMinutes:60,targetRpe:6,goal:'',notes:'',personalGoalId:null,trainingCycleId:null,changeReason:'Creación inicial de la sesión'})}
function editSession(){if(!selected.value)return;editingSessionId.value=selected.value.id;Object.assign(sessionForm,{date:selected.value.date,name:selected.value.name,activityType:selected.value.activityType,plannedStartTime:selected.value.plannedStartTime?.slice(0,5)??null,plannedDurationMinutes:selected.value.plannedDurationMinutes,targetRpe:selected.value.targetRpe,goal:selected.value.goal??'',notes:selected.value.notes??'',personalGoalId:selected.value.personalGoalId,trainingCycleId:selected.value.trainingCycleId,changeReason:''});showNew.value=true;scrollTo({top:0,behavior:'smooth'})}
async function create(){try{const s=editingSessionId.value?await api.updateSession(editingSessionId.value,sessionForm):await api.createSession(sessionForm);sync(s);success.value=editingSessionId.value?'Sesión actualizada y versionada.':'Sesión planificada.';resetSession()}catch(e){setError(e)}}
function openDuplicate(){if(!selected.value)return;Object.assign(duplicateForm,{date:tomorrow(),name:selected.value.name,changeReason:'Sesión reutilizada desde una planificación existente'});showDuplicate.value=true}
async function duplicate(){if(!selected.value)return;duplicating.value=true;error.value='';try{const copy=await api.duplicateSession(selected.value.id,duplicateForm);showDuplicate.value=false;await load();selectedId.value=copy.id;hydrateResults(copy);success.value='Sesión duplicada. La planificación se conservó y los resultados comenzaron vacíos.'}catch(e){setError(e)}finally{duplicating.value=false}}
async function copyWeek(){copyingWeek.value=true;error.value='';try{const result=await api.copyTrainingWeek(weekForm);showWeekCopy.value=false;await load();if(result.sessions[0]){selectedId.value=result.sessions[0].id;hydrateResults(result.sessions[0])}success.value=`Semana preparada: ${result.copiedSessions} sesiones nuevas${result.skippedSessions?` y ${result.skippedSessions} ya existentes omitidas`:''}.`}catch(e){setError(e)}finally{copyingWeek.value=false}}
function resetExercise(){editingExerciseId.value=null;addingExercise.value=false;Object.assign(exerciseForm,{name:'',category:'Fuerza',sets:3,repetitions:'10',loadKg:null,restSeconds:90,notes:'',changeReason:'Ejercicio agregado a la prescripción'})}
function editExercise(x:TrainingSession['exercises'][number]){editingExerciseId.value=x.id;Object.assign(exerciseForm,{name:x.name,category:x.category??'',sets:x.plannedSets,repetitions:x.plannedRepetitions,loadKg:x.plannedLoadKg,restSeconds:x.restSeconds,notes:x.notes??'',changeReason:''});addingExercise.value=true}
async function add(){if(!selected.value)return;try{sync(editingExerciseId.value?await api.updateExercise(selected.value.id,editingExerciseId.value,exerciseForm):await api.addExercise(selected.value.id,exerciseForm));resetExercise()}catch(e){setError(e)}}
async function start(){if(!selected.value)return;try{sync(await api.startSession(selected.value.id))}catch(e){setError(e)}}
async function record(id:string){if(!selected.value)return;try{sync(await api.recordExercise(selected.value.id,id,resultForms[id]))}catch(e){setError(e)}}
async function complete(){if(!selected.value)return;try{if(!auth.user)throw new Error('La sesión debe estar activa para guardar un pendiente.');const result=await api.completeSessionResilient(selected.value.id,completeForm,auth.user.id);completing.value=false;if(result.queued){success.value='Cierre guardado en este dispositivo. Atlas lo sincronizará al recuperar conexión.';return}sync(result.data);success.value='Sesión guardada. Atlas habilitará el control posterior.';await load()}catch(e){setError(e)}}
function reloadAfterSync(){void load()}
onMounted(()=>{void load();window.addEventListener('atlas-sync-complete',reloadAfterSync)})
onUnmounted(()=>window.removeEventListener('atlas-sync-complete',reloadAfterSync))
</script>
<template>
<section class="page training-page" :class="{muted:loading}">
 <div class="page-heading"><div><span class="eyebrow">Proyecto Atlas</span><h1>Entrenamiento personal</h1><p>Planificá, ejecutá y compará cada sesión con tu respuesta posterior.</p></div><div class="heading-actions"><button class="secondary-button" @click="showWeekCopy=!showWeekCopy">Copiar semana</button><button class="primary-button" @click="showNew=!showNew">Nueva sesión</button></div></div>
 <div v-if="error" class="notice error">{{error}}</div><div v-if="success" class="notice atlas-success">{{success}}</div>
 <div v-if="overview" class="training-metrics"><article><span>Sesiones · 7 días</span><strong>{{overview.metrics.sessionsLast7Days}}</strong></article><article><span>Minutos · 7 días</span><strong>{{overview.metrics.minutesLast7Days}}</strong></article><article><span>Carga interna</span><strong>{{overview.metrics.loadLast7Days}}</strong></article><article :class="{warning:overview.metrics.pendingFollowUps}"><span>Controles pendientes</span><strong>{{overview.metrics.pendingFollowUps}}</strong></article></div>
 <form v-if="showWeekCopy" class="panel training-form week-copy-form" @submit.prevent="copyWeek"><div><span class="eyebrow">Semana como plantilla</span><h2>Copiar planificación semanal</h2><p>Atlas conserva días relativos, sesiones, ejercicios y vínculos del plan. Los resultados y respuestas posteriores comienzan vacíos.</p></div><div class="atlas-form-grid"><label>Inicio de semana de origen<input v-model="weekForm.sourceWeekStart" type="date" required></label><label>Inicio de semana de destino<input v-model="weekForm.targetWeekStart" type="date" required></label><label class="wide">Motivo<input v-model="weekForm.changeReason" required></label></div><div class="form-actions"><button type="button" class="secondary-button" @click="showWeekCopy=false">Cancelar</button><button class="primary-button" :disabled="copyingWeek">{{copyingWeek?'Preparando…':'Copiar planificación'}}</button></div></form>
 <form v-if="showNew" class="panel training-form" @submit.prevent="create"><div class="panel-heading"><div><span class="eyebrow">Planificación trazable</span><h2>{{editingSessionId?'Corregir sesión':'Nueva sesión'}}</h2></div></div><div class="atlas-form-grid"><label>Fecha<input v-model="sessionForm.date" type="date" required></label><label>Hora prevista<input v-model="sessionForm.plannedStartTime" type="time"><small>Opcional</small></label><label>Nombre<input v-model="sessionForm.name" required placeholder="Ej.: Fuerza de tren inferior"></label><label>Actividad<select v-model="sessionForm.activityType"><option>Fuerza</option><option>Cardio</option><option>Taekwondo</option><option>Movilidad</option><option>Recuperación</option><option>Otra</option></select></label><label>Duración prevista<input v-model.number="sessionForm.plannedDurationMinutes" type="number" min="1" max="600"></label><label>RPE objetivo<select v-model.number="sessionForm.targetRpe"><option v-for="n in 10" :key="n" :value="n">{{n}} / 10</option></select></label><label>Objetivo específico<input v-model="sessionForm.goal"></label><label>Objetivo maestro<select v-model="sessionForm.personalGoalId"><option :value="null">Sin vincular</option><option v-for="x in overview.goals" :key="x.id" :value="x.id">{{x.name}}</option></select></label><label>Ciclo<select v-model="sessionForm.trainingCycleId"><option :value="null">Sin vincular</option><option v-for="x in overview.cycles" :key="x.id" :value="x.id">{{x.name}}</option></select></label><label class="wide">Motivo de esta versión<input v-model="sessionForm.changeReason" required placeholder="Por qué se crea o corrige"></label></div><label>Notas<textarea v-model="sessionForm.notes" rows="2"></textarea></label><div class="form-actions"><button type="button" class="secondary-button" @click="resetSession">Cancelar</button><button class="primary-button">{{editingSessionId?'Actualizar versión':'Guardar planificación'}}</button></div></form>
 <div v-if="overview" class="training-workspace">
  <aside class="panel training-list"><div class="panel-heading"><div><span class="eyebrow">Agenda</span><h2>Sesiones</h2></div></div><button v-for="s in [...overview.upcoming,...overview.recent]" :key="s.id" :class="{active:s.id===selectedId}" @click="selectedId=s.id;hydrateResults(s)"><span><strong>{{s.name}}</strong><small>{{fmt(s.date)}} · {{s.activityType}}</small></span><em :class="s.status.toLowerCase()">{{s.status==='Planned'?'Planificada':s.status==='InProgress'?'En curso':'Completada'}}</em></button><p v-if="!overview.upcoming.length&&!overview.recent.length" class="list-empty">Creá tu primera sesión para empezar.</p></aside>
  <main v-if="selected" class="training-detail">
   <article class="panel training-session-head"><div><span class="eyebrow">{{fmt(selected.date)}}<template v-if="selected.plannedStartTime"> · {{selected.plannedStartTime.slice(0,5)}}</template> · {{selected.activityType}} · v{{selected.version}}</span><h2>{{selected.name}}</h2><p>{{selected.goal||'Sin objetivo específico'}}</p><small v-if="selected.personalGoalTitle">Objetivo: {{selected.personalGoalTitle}}</small><small v-if="selected.trainingCycleName"> · Ciclo: {{selected.trainingCycleName}}</small></div><div><div class="session-target"><span>Objetivo</span><strong>{{selected.plannedDurationMinutes??'—'}} min · RPE {{selected.targetRpe??'—'}}</strong></div><div class="session-head-actions"><button v-if="selected.status==='Planned'" class="small-button" @click="editSession">Editar</button><button class="small-button" @click="openDuplicate">Duplicar</button></div></div></article>
   <form v-if="showDuplicate" class="panel duplicate-session-form" @submit.prevent="duplicate"><div><span class="eyebrow">Reutilizar planificación</span><h2>Duplicar sesión</h2><p>Se copiarán la prescripción, el objetivo y el ciclo. Los resultados, el esfuerzo real y la respuesta posterior quedarán vacíos.</p></div><div class="atlas-form-grid"><label>Nueva fecha<input v-model="duplicateForm.date" type="date" :min="today" required></label><label>Nombre<input v-model="duplicateForm.name" required></label><label class="wide">Motivo<input v-model="duplicateForm.changeReason" required></label></div><div class="form-actions"><button type="button" class="secondary-button" @click="showDuplicate=false">Cancelar</button><button class="primary-button" :disabled="duplicating">{{duplicating?'Duplicando…':'Crear copia limpia'}}</button></div></form>
   <article v-if="selected.status!=='Completed'" class="panel"><div class="panel-heading"><div><span class="eyebrow">Contenido</span><h2>Ejercicios</h2></div><button class="secondary-button" @click="addingExercise=!addingExercise">Agregar ejercicio</button></div>
    <form v-if="addingExercise" class="exercise-entry" @submit.prevent="add"><label>Ejercicio<input v-model="exerciseForm.name" required></label><label>Categoría<input v-model="exerciseForm.category"></label><label>Series<input v-model.number="exerciseForm.sets" type="number" min="1"></label><label>Repeticiones<input v-model="exerciseForm.repetitions" required></label><label>Carga (kg)<input v-model.number="exerciseForm.loadKg" type="number" min="0" step="0.5"></label><label>Descanso (s)<input v-model.number="exerciseForm.restSeconds" type="number" min="0"></label><label class="wide">Indicaciones<input v-model="exerciseForm.notes"></label><label class="wide">Motivo del cambio<input v-model="exerciseForm.changeReason" required></label><div class="form-actions wide"><button type="button" class="secondary-button" @click="resetExercise">Cancelar</button><button class="primary-button">{{editingExerciseId?'Actualizar':'Agregar'}}</button></div></form>
    <div class="training-exercises"><div v-for="x in selected.exercises" :key="x.id" class="training-exercise"><span>{{x.order}}</span><div><strong>{{x.name}}</strong><small>{{x.plannedSets}} × {{x.plannedRepetitions}}<template v-if="x.plannedLoadKg"> · {{x.plannedLoadKg}} kg</template><template v-if="x.restSeconds"> · {{x.restSeconds}} s</template></small><p v-if="x.notes">{{x.notes}}</p></div><button v-if="selected.status==='Planned'" class="small-button" @click="editExercise(x)">Editar</button></div><p v-if="!selected.exercises.length" class="list-empty">Todavía no agregaste ejercicios. También podés registrar cardio o taekwondo sin ejercicios.</p></div>
   </article>
   <article v-if="selected.status==='Planned'" class="panel session-action"><div><h2>¿Listo para empezar?</h2><p>Podrás registrar lo realmente realizado ejercicio por ejercicio.</p></div><button class="primary-button" @click="start">Iniciar sesión</button></article>
   <article v-if="selected.status==='InProgress'" class="panel"><div class="panel-heading"><div><span class="eyebrow">Ejecución</span><h2>Registrar resultados</h2></div></div><form v-for="x in selected.exercises" :key="x.id" class="result-row" @submit.prevent="record(x.id)"><strong>{{x.name}}</strong><label>Series<input v-model.number="resultForms[x.id].completedSets" type="number" min="0"></label><label>Repeticiones<input v-model="resultForms[x.id].actualRepetitions"></label><label>Carga<input v-model.number="resultForms[x.id].actualLoadKg" type="number" min="0" step="0.5"></label><label>RPE<input v-model.number="resultForms[x.id].exerciseRpe" type="number" min="1" max="10"></label><button class="secondary-button">Guardar</button></form><div class="session-action"><div><h2>Cerrar entrenamiento</h2><p>Usaremos duración × RPE como carga interna simple.</p></div><button class="primary-button" @click="completing=!completing">Completar sesión</button></div><form v-if="completing" class="complete-form" @submit.prevent="complete"><label>Duración real<input v-model.number="completeForm.actualDurationMinutes" type="number" min="1" required></label><label>RPE global<select v-model.number="completeForm.sessionRpe"><option v-for="n in 10" :value="n">{{n}} / 10</option></select></label><label class="wide">Notas<textarea v-model="completeForm.completionNotes" rows="2"></textarea></label><button class="primary-button">Guardar y cerrar</button></form></article>
   <article v-if="selected.status==='Completed'" class="panel completed-summary"><span class="eyebrow">Sesión completada</span><h2>{{selected.actualDurationMinutes}} min × RPE {{selected.sessionRpe}} = {{selected.internalLoad}} UA</h2><p>{{selected.completionNotes||'Sin notas adicionales.'}}</p><RouterLink v-if="selected.followUpDue&&!selected.followUp" class="primary-button" to="/respuesta-24h">Registrar respuesta posterior</RouterLink><span v-else-if="selected.followUp" class="evidence-chip">Respuesta posterior registrada</span><p v-else>El control posterior se habilita aproximadamente 20–24 horas después.</p></article>
  </main><article v-else class="panel empty-state"><h2>Seleccioná una sesión</h2></article>
 </div>
</section>
</template>
