<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { getTrainingOverview, saveFollowUp } from '../services/trainingService'
import type { TrainingOverview } from '../types/training'
const overview=ref<TrainingOverview|null>(null), selectedId=ref(''), error=ref(''), success=ref(''), loading=ref(true)
const form=reactive({recovery:3,painIntensity:null as number|null,painLocation:'',stiffness:'ninguna',swelling:'ninguna',instability:false,locking:false,notes:''})
const selected=computed(()=>overview.value?.pendingFollowUps.find(x=>x.id===selectedId.value)??null)
async function load(){loading.value=true;try{overview.value=await getTrainingOverview();selectedId.value=overview.value.pendingFollowUps[0]?.id??''}catch(e){error.value=e instanceof Error?e.message:'No se pudo cargar.'}finally{loading.value=false}}
async function submit(){if(!selected.value)return;try{const saved=await saveFollowUp(selected.value.id,form);success.value=saved.needsAttention?'Registro guardado. Hay señales que merecen seguimiento y, si persisten o empeoran, consulta profesional.':'Respuesta guardada. Atlas la relacionará con esa sesión.';await load()}catch(e){error.value=e instanceof Error?e.message:'No se pudo guardar.'}}
onMounted(load)
</script>
<template><section class="page followup-page" :class="{muted:loading}"><div class="page-heading"><div><span class="eyebrow">Respuesta posterior</span><h1>Control a las 24 horas</h1><p>Relacioná la carga realizada con cómo respondió tu cuerpo después.</p></div></div><div v-if="error" class="notice error">{{error}}</div><div v-if="success" class="notice atlas-success">{{success}}</div><div v-if="overview?.pendingFollowUps.length" class="followup-layout"><aside class="panel training-list"><div class="panel-heading"><div><span class="eyebrow">Pendientes</span><h2>Sesiones</h2></div><span class="badge">{{overview.pendingFollowUps.length}}</span></div><button v-for="s in overview.pendingFollowUps" :key="s.id" :class="{active:s.id===selectedId}" @click="selectedId=s.id"><span><strong>{{s.name}}</strong><small>{{s.date}} · {{s.actualDurationMinutes}} min · RPE {{s.sessionRpe}}</small></span></button></aside><form v-if="selected" class="panel followup-form" @submit.prevent="submit"><div class="panel-heading"><div><span class="eyebrow">{{selected.name}}</span><h2>¿Cómo respondiste?</h2></div><span class="evidence-chip">Autorreporte posterior</span></div><p>Este control ayuda a reconocer patrones. No diagnostica lesiones ni reemplaza una evaluación médica.</p><div class="atlas-form-grid"><label>Recuperación<select v-model.number="form.recovery"><option v-for="n in 5" :value="n">{{n}} / 5</option></select></label><label>Dolor<select v-model.number="form.painIntensity"><option :value="null">Sin registrar</option><option v-for="n in 11" :value="n-1">{{n-1}} / 10</option></select></label><label>Zona<input v-model="form.painLocation" placeholder="Ej.: rodilla izquierda"></label><label>Rigidez<select v-model="form.stiffness"><option>ninguna</option><option>leve</option><option>moderada</option><option>alta</option></select></label><label>Inflamación<select v-model="form.swelling"><option>ninguna</option><option>leve</option><option>moderada</option><option>alta</option></select></label></div><div class="atlas-flag-row"><label><input v-model="form.instability" type="checkbox"> Sensación de falseo</label><label><input v-model="form.locking" type="checkbox"> Bloqueo</label></div><label>Notas<textarea v-model="form.notes" rows="3" placeholder="Cambios respecto de antes de entrenar"></textarea></label><div class="atlas-submit-row"><span>Compararemos esta respuesta con la sesión, no con otras personas.</span><button class="primary-button">Guardar respuesta</button></div></form></div><article v-else-if="!loading" class="panel empty-state followup-empty"><span class="empty-icon">✓</span><h2>No hay controles pendientes</h2><p>Cuando una sesión completada cumpla aproximadamente 20–24 horas aparecerá aquí.</p><RouterLink class="secondary-button" to="/entrenamiento">Volver a entrenamiento</RouterLink></article></section></template>
