export type PendingKind = 'daily-check-in' | 'training-completion'
export interface PendingOperation { id:string; ownerId:string; kind:PendingKind; url:string; method:'PUT'|'POST'; body:unknown; createdAt:string; attempts:number; lastError:string|null }

const databaseName='atlas-private-queue',storeName='pending-operations'

function database():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(databaseName,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(storeName)){const store=db.createObjectStore(storeName,{keyPath:'id'});store.createIndex('ownerId','ownerId')}};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function transaction<T>(mode:IDBTransactionMode,action:(store:IDBObjectStore,resolve:(value:T)=>void,reject:(reason?:unknown)=>void)=>void):Promise<T>{const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction(storeName,mode);action(tx.objectStore(storeName),resolve,reject);tx.oncomplete=()=>db.close();tx.onerror=()=>reject(tx.error)})}
function notify(){window.dispatchEvent(new CustomEvent('atlas-queue-change'))}

export async function queueOperation(operation:Omit<PendingOperation,'createdAt'|'attempts'|'lastError'>){const safeBody=JSON.parse(JSON.stringify(operation.body)) as unknown;await transaction<void>('readwrite',(store,resolve,reject)=>{const request=store.put({...operation,body:safeBody,createdAt:new Date().toISOString(),attempts:0,lastError:null});request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)});notify()}
export async function pendingFor(ownerId:string):Promise<PendingOperation[]>{return transaction<PendingOperation[]>('readonly',(store,resolve,reject)=>{const request=store.index('ownerId').getAll(ownerId);request.onsuccess=()=>resolve(request.result as PendingOperation[]);request.onerror=()=>reject(request.error)})}
async function remove(id:string){await transaction<void>('readwrite',(store,resolve,reject)=>{const request=store.delete(id);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)})}
async function update(operation:PendingOperation){await transaction<void>('readwrite',(store,resolve,reject)=>{const request=store.put(operation);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)})}

export async function syncPending(ownerId:string){if(!navigator.onLine)return{synced:0,pending:(await pendingFor(ownerId)).length};let synced=0;for(const operation of await pendingFor(ownerId)){try{const response=await fetch(operation.url,{method:operation.method,credentials:'include',headers:{'Content-Type':'application/json','X-Atlas-Queued-At':operation.createdAt},body:JSON.stringify(operation.body)});if(response.ok){await remove(operation.id);synced++;continue}if(response.status===401)break;operation.attempts++;operation.lastError=`Respuesta ${response.status}`;await update(operation)}catch(error){operation.attempts++;operation.lastError=error instanceof Error?error.message:'Sin conexión';await update(operation);break}}const pending=(await pendingFor(ownerId)).length;notify();if(synced)window.dispatchEvent(new CustomEvent('atlas-sync-complete',{detail:{synced,pending}}));return{synced,pending}}
