import type{CreatedReportShare,ProfessionalReport,ReportFeedback,ReportShare,SharedProfessionalReport}from'../types/report';
async function result<T>(r:Response,message:string){if(!r.ok){const b=await r.json().catch(()=>null)as{message?:string}|null;throw new Error(b?.message??message)}return r.json()as Promise<T>}
export async function getProfessionalReport(from:string,to:string){return result<ProfessionalReport>(await fetch(`/api/reports/professional?from=${from}&to=${to}`,{credentials:'include'}),'No se pudo generar el informe.')}
export async function createReportShare(body:{from:string;to:string;expiresInDays:number;includeKnee:boolean;includeLearning:boolean;recipientLabel:string;consent:boolean}){return result<CreatedReportShare>(await fetch('/api/reports/shares',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),'No se pudo crear el enlace.')}
export async function listReportShares(){return result<ReportShare[]>(await fetch('/api/reports/shares',{credentials:'include'}),'No se pudieron cargar los enlaces.')}
export async function revokeReportShare(id:string){const r=await fetch(`/api/reports/shares/${id}`,{method:'DELETE',credentials:'include'});if(!r.ok)throw new Error('No se pudo revocar el enlace.')}
export async function getSharedReport(token:string){return result<SharedProfessionalReport>(await fetch(`/api/reports/shared/${encodeURIComponent(token)}`),'El enlace no existe, venció o fue revocado.')}
export async function submitReportFeedback(token:string,body:{authorName:string;kind:string;section:string;message:string}){return result<{id:string;createdAt:string}>(await fetch(`/api/reports/shared/${encodeURIComponent(token)}/feedback`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),'No se pudo enviar el aporte.')}
export async function listReportFeedback(){return result<ReportFeedback[]>(await fetch('/api/reports/feedback',{credentials:'include'}),'No se pudieron cargar los aportes.')}
export async function reviewReportFeedback(id:string,body:{status:string;decisionNote:string}){const r=await fetch(`/api/reports/feedback/${id}`,{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const b=await r.json().catch(()=>null)as{message?:string}|null;throw new Error(b?.message??'No se pudo registrar la decisión.')}}
