using Gimnasio.Application.Planning;using Gimnasio.Domain.Entities;using Gimnasio.Infrastructure.Persistence;using Microsoft.EntityFrameworkCore;
namespace Gimnasio.Infrastructure.Planning;
internal sealed class PlanningService(GimnasioDbContext db):IPlanningService
{
 public async Task<PlanningOverviewDto>GetAsync(Guid userId,CancellationToken ct=default)
 {
  var pid=await Profile(userId,ct);var goals=await db.PersonalGoals.AsNoTracking().Where(x=>x.AthleteProfileId==pid&&x.IsActive).OrderBy(x=>x.Status).ThenBy(x=>x.TargetDate).ToListAsync(ct);var cycles=await db.TrainingCycles.AsNoTracking().Where(x=>x.AthleteProfileId==pid&&x.IsActive).OrderByDescending(x=>x.StartDate).ToListAsync(ct);var changes=await db.PlanChanges.AsNoTracking().Where(x=>x.AthleteProfileId==pid).OrderByDescending(x=>x.CreatedAt).Take(50).ToListAsync(ct);var metrics=await db.MetricDefinitions.AsNoTracking().Where(x=>x.AthleteProfileId==pid&&x.IsActive).OrderBy(x=>x.Name).ToListAsync(ct);var metricIds=metrics.Select(x=>x.Id).ToArray();var entries=await db.MeasurementEntries.AsNoTracking().Where(x=>metricIds.Contains(x.MetricDefinitionId)&&x.IsActive).OrderBy(x=>x.Date).ToListAsync(ct);var cycleIds=cycles.Select(x=>x.Id).ToArray();var sessions=await db.TrainingSessions.AsNoTracking().Where(x=>x.AthleteProfileId==pid&&x.TrainingCycleId.HasValue&&cycleIds.Contains(x.TrainingCycleId.Value)).ToListAsync(ct);
  return new(goals.Select(x=>Map(x,metrics.FirstOrDefault(m=>m.Id==x.MetricDefinitionId),entries.Where(e=>e.MetricDefinitionId==x.MetricDefinitionId))).ToArray(),cycles.Select(x=>Map(x,sessions.Where(s=>s.TrainingCycleId==x.Id))).ToArray(),changes.Select(x=>new PlanChangeDto(x.Id,x.EntityType,x.EntityId,x.Version,x.Reason,x.Summary,x.CreatedAt)).ToArray(),metrics.Select(x=>new MetricOptionDto(x.Id,x.Name,x.Unit,x.Direction.ToString())).ToArray());
 }
 public async Task<GoalDto>SaveGoalAsync(Guid userId,Guid? id,SaveGoalRequest r,CancellationToken ct=default){var pid=await Profile(userId,ct);if(r.MetricDefinitionId.HasValue&&!await db.MetricDefinitions.AnyAsync(x=>x.Id==r.MetricDefinitionId&&x.AthleteProfileId==pid&&x.IsActive,ct))throw new ArgumentException("El indicador no pertenece al perfil.");PersonalGoal x;var update=id.HasValue;if(update)x=await db.PersonalGoals.SingleOrDefaultAsync(x=>x.Id==id&&x.AthleteProfileId==pid&&x.IsActive,ct)??throw new KeyNotFoundException();else{x=new(pid,r.Title);db.PersonalGoals.Add(x);}x.Configure(r.Title,r.Category,r.BaselineValue,r.TargetValue,r.Unit,r.StartDate,r.TargetDate,r.Status,r.Rationale,update);x.LinkMetric(r.MetricDefinitionId);db.PlanChanges.Add(new(pid,"goal",x.Id,x.Version,r.ChangeReason,$"{x.Title} · {x.Status}"));await db.SaveChangesAsync(ct);var metric=r.MetricDefinitionId.HasValue?await db.MetricDefinitions.AsNoTracking().SingleAsync(m=>m.Id==r.MetricDefinitionId,ct):null;var entries=metric is null?[]:await db.MeasurementEntries.AsNoTracking().Where(e=>e.MetricDefinitionId==metric.Id&&e.IsActive).OrderBy(e=>e.Date).ToListAsync(ct);return Map(x,metric,entries);}
 public async Task<CycleDto>SaveCycleAsync(Guid userId,Guid? id,SaveCycleRequest r,CancellationToken ct=default){var pid=await Profile(userId,ct);TrainingCycle x;var update=id.HasValue;if(update)x=await db.TrainingCycles.SingleOrDefaultAsync(x=>x.Id==id&&x.AthleteProfileId==pid&&x.IsActive,ct)??throw new KeyNotFoundException();else{x=new(pid,r.Name);db.TrainingCycles.Add(x);}x.Configure(r.Name,r.StartDate,r.EndDate,r.Focus,r.PlannedSessionsPerWeek,r.Status,r.Notes,update);db.PlanChanges.Add(new(pid,"cycle",x.Id,x.Version,r.ChangeReason,$"{x.Name} · {x.Focus} · {x.Status}"));await db.SaveChangesAsync(ct);var sessions=await db.TrainingSessions.AsNoTracking().Where(s=>s.TrainingCycleId==x.Id).ToListAsync(ct);return Map(x,sessions);}
 private async Task<Guid>Profile(Guid uid,CancellationToken ct)=>(await db.AthleteProfiles.AsNoTracking().SingleOrDefaultAsync(x=>x.UserId==uid,ct))?.Id??throw new InvalidOperationException("Primero debe inicializarse el perfil Atlas.");
 private static GoalDto Map(PersonalGoal x,MetricDefinition? metric,IEnumerable<MeasurementEntry> source){var entries=source.OrderBy(e=>e.Date).ToArray();var latest=entries.LastOrDefault();var baseline=x.BaselineValue??entries.FirstOrDefault()?.Value;decimal? progress=null;if(baseline.HasValue&&x.TargetValue.HasValue&&latest is not null&&x.TargetValue!=baseline)progress=Math.Round(Math.Clamp((latest.Value-baseline.Value)/(x.TargetValue.Value-baseline.Value)*100m,0,100),1);return new(x.Id,x.Title,x.Category,x.BaselineValue,x.TargetValue,x.Unit,x.StartDate,x.TargetDate,x.Status,x.Rationale,x.Version,x.MetricDefinitionId,metric?.Name,latest?.Value,latest?.Date,progress);}
 private static CycleDto Map(TrainingCycle x,IEnumerable<TrainingSession> source){var today=DateOnly.FromDateTime(DateTime.Today);var until=today<x.StartDate?x.StartDate.AddDays(-1):today>x.EndDate?x.EndDate:today;var elapsed=until<x.StartDate?0:until.DayNumber-x.StartDate.DayNumber+1;var expected=elapsed==0?0:(int)Math.Ceiling(elapsed/7m*x.PlannedSessionsPerWeek);var completed=source.Count(s=>s.Status==Gimnasio.Domain.Enums.TrainingSessionStatus.Completed&&s.Date>=x.StartDate&&s.Date<=until);decimal? adherence=expected==0?null:Math.Round(completed*100m/expected,1);return new(x.Id,x.Name,x.StartDate,x.EndDate,x.Focus,x.PlannedSessionsPerWeek,x.Status,x.Notes,x.Version,expected,completed,adherence);}
}
