export interface DailyTrend { date:string; internalLoad:number; sleepQuality:number|null; energy:number|null; fatigue:number|null; stress:number|null; pain:number|null; recovery:number|null }
export interface InsightSignal { kind:'info'|'observe'|'attention'|'neutral'; title:string; detail:string; basis:string }
export interface InsightEvidence { topic:string; title:string; permanentId:string; sourceUrl:string; use:string; limitation:string }
export interface DecisionOutcome{date:string;decision:'as-planned'|'adjusted'|'recovery'|'professional-review';reason:string;contextStatus:string;plannedLoad:number;trainingLoad:number;externalLoad:number;totalLoad:number;pain:number|null;fatigue:number|null;hasPostSessionAttention:boolean;version:number}
export interface LearningTrend{reviewedActions:number;helpful:number;neutral:number;notHelpful:number;inconclusive:number;openActions:number;dueActions:number;categories:{category:string;reviewedActions:number}[];patterns:{category:string;entries:number;dominantOutcome:'helpful'|'neutral'|'not-helpful'|'inconclusive';outcomeCount:number;sharePercent:number;state:'repeated'|'mixed'}[];disclaimer:string}
export interface PersonalVariabilityFactor{key:string;label:string;unit:string;entries:number;median:number;lowerQuartile:number;upperQuartile:number;minimum:number;maximum:number}
export interface PersonalVariability{windowDays:number;checkInDays:number;coveragePercent:number;factors:PersonalVariabilityFactor[];disclaimer:string}
export interface PersonalPeriodComparisonFactor{key:string;label:string;unit:string;recentEntries:number;baselineEntries:number;recentMedian:number;baselineMedian:number;baselineLowerQuartile:number;baselineUpperQuartile:number;delta:number;position:'below'|'within'|'above'|'insufficient'}
export interface PersonalPeriodComparison{recentDays:number;baselineDays:number;recentCheckIns:number;baselineCheckIns:number;recentCoveragePercent:number;baselineCoveragePercent:number;comparableFactors:number;factors:PersonalPeriodComparisonFactor[];disclaimer:string}
export interface InsightsOverview { days:DailyTrend[]; load:{current7Days:number;previous7Days:number;changePercent:number|null;sessionsCurrent7Days:number;minutesCurrent7Days:number}; wellbeing:{averageSleepQuality:number|null;averageEnergy:number|null;averageFatigue:number|null;averageStress:number|null;averagePain:number|null;averageRecovery:number|null}; variability:PersonalVariability; periodComparison:PersonalPeriodComparison; signals:InsightSignal[]; decisions:DecisionOutcome[]; learning:LearningTrend; evidence:InsightEvidence[]; dataDays:number; hasEnoughData:boolean }
