export interface TrainingExercise { id:string; order:number; name:string; category:string|null; plannedSets:number; plannedRepetitions:string; plannedLoadKg:number|null; restSeconds:number|null; notes:string|null; completedSets:number|null; actualRepetitions:string|null; actualLoadKg:number|null; exerciseRpe:number|null; isCompleted:boolean }
export interface TrainingFollowUp { id:string; recordedAt:string; recovery:number; painIntensity:number|null; painLocation:string|null; stiffness:string|null; swelling:string|null; instability:boolean; locking:boolean; notes:string|null; needsAttention:boolean }
export interface TrainingSession { id:string; date:string; name:string; activityType:string; plannedStartTime:string|null; plannedDurationMinutes:number|null; targetRpe:number|null; goal:string|null; notes:string|null; personalGoalId:string|null;personalGoalTitle:string|null;trainingCycleId:string|null;trainingCycleName:string|null;version:number; status:'Planned'|'InProgress'|'Completed'|'Cancelled'; actualDurationMinutes:number|null; sessionRpe:number|null; internalLoad:number|null; completionNotes:string|null; completedAt:string|null; followUpDue:boolean; followUp:TrainingFollowUp|null; exercises:TrainingExercise[] }
export interface TrainingOverview { upcoming:TrainingSession[]; recent:TrainingSession[]; pendingFollowUps:TrainingSession[]; metrics:{ sessionsLast7Days:number; minutesLast7Days:number; loadLast7Days:number; pendingFollowUps:number };goals:{id:string;name:string;detail:string}[];cycles:{id:string;name:string;detail:string}[] }
export interface CopyTrainingWeekResult { copiedSessions:number; skippedSessions:number; sessions:TrainingSession[] }
export interface CalendarSession { id:string; name:string; activityType:string; status:'Planned'|'InProgress'|'Completed'|'Cancelled'; plannedStartTime:string|null; plannedEndTime:string|null; plannedDurationMinutes:number|null; targetRpe:number|null; actualDurationMinutes:number|null; sessionRpe:number|null; followUpPending:boolean }
export interface CalendarLearningReview { id:string; title:string; nextAction:string; status:'open'|'applied'|'archived'; reviewDueOn:string; reviewedOn:string|null; isDue:boolean }
export interface ScheduleBlock { id:string; dayOfWeek:number; name:string; category:string; timeWindow:'exact'|'morning'|'afternoon'|'evening'|'flexible'; startTime:string|null; endTime:string|null; effectiveFrom:string; effectiveTo:string|null; notes:string|null }
export interface TrainingCalendarDay { date:string; hasCheckIn:boolean; energy:number|null; fatigue:number|null; pain:number|null; plannedMinutes:number; actualMinutes:number; internalLoad:number; externalLoad:number; totalLoad:number; dailyActivities:number; sessions:CalendarSession[]; learningReviews:CalendarLearningReview[]; scheduleBlocks:ScheduleBlock[]; hasScheduleConflict:boolean }
export interface TrainingCalendar { from:string; to:string; days:TrainingCalendarDay[]; summary:{plannedSessions:number;completedSessions:number;plannedMinutes:number;actualMinutes:number;internalLoad:number;externalLoad:number;totalLoad:number;checkInDays:number;scheduledLearningReviews:number;dueLearningReviews:number} }
